// Mocks generated by Mockito 5.0.16 from annotations
// in flutter_sandbox/test/features/beers/domain/usecase/get_beers_usecase_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:flutter_sandbox/src/features/beers/domain/model/beer_preview.dart'
    as _i5;
import 'package:flutter_sandbox/src/features/beers/domain/repository/beers_repository.dart'
    as _i3;
import 'package:flutter_sandbox/src/libraries/core/data_result.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeDataResult_0<T> extends _i1.Fake implements _i2.DataResult<T> {}

/// A class which mocks [IsBeersRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIsBeersRepository extends _i1.Mock implements _i3.IsBeersRepository {
  MockIsBeersRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataResult<List<_i5.BeerPreview>>> getBeers(
          {int? page, int? perPage}) =>
      (super.noSuchMethod(
          Invocation.method(#getBeers, [], {#page: page, #perPage: perPage}),
          returnValue: Future<_i2.DataResult<List<_i5.BeerPreview>>>.value(
              _FakeDataResult_0<List<_i5.BeerPreview>>())) as _i4
          .Future<_i2.DataResult<List<_i5.BeerPreview>>>);
  @override
  String toString() => super.toString();
}
